'use client';
import {useCallback,useEffect,useState} from 'react';
type Member={id:string;email:string;status:'pending'|'active'|'suspended';role:string;created_at:string};
const labels={pending:'승인 대기',active:'이용 중',suspended:'이용 중지'};
export default function Members(){const [members,setMembers]=useState<Member[]>([]);const [page,setPage]=useState(0);const [count,setCount]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin?page='+page);const d=await r.json();if(!r.ok)throw Error(d.error);setMembers(d.members);setCount(d.count);}catch(e){setError(e instanceof Error?e.message:'불러오기 실패');}finally{setLoading(false);}},[page]);useEffect(()=>{void load();},[load]);
 async function update(m:Member,status:Member['status']){if(status==='suspended'&&!window.confirm(m.email+'님의 이용을 중지할까요?'))return;setBusy(m.id);setError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:m.id,status})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:'변경 실패');}finally{setBusy('');}}
 return <main className="admin-shell"><div className="admin-heading"><div><span className="auth-eyebrow">GLOBALVIRAL ADMIN</span><h1>수강생 관리</h1><p>가입 신청을 확인하고 작업실 이용 권한을 관리합니다.</p></div><a href="/">← 작업실로</a></div>{error&&<p className="auth-error" role="alert">{error}</p>}<div className="admin-table"><table><thead><tr><th>이메일</th><th>가입일</th><th>상태</th><th>권한 관리</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td>{m.email}{m.role==='admin'&&<small> · 운영자</small>}</td><td>{new Date(m.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</td><td><span className={'member-status '+m.status}>{labels[m.status]}</span></td><td>{m.role==='student'&&<div className="member-actions">{m.status!=='active'&&<button disabled={!!busy} onClick={()=>update(m,'active')}>승인</button>}{m.status==='active'&&<button disabled={!!busy} onClick={()=>update(m,'suspended')}>이용 중지</button>}</div>}</td></tr>)}</tbody></table>{loading?<p>불러오는 중…</p>:!members.length&&<p>가입한 수강생이 없습니다.</p>}</div><div className="admin-pagination"><button disabled={page===0||loading||!!busy} onClick={()=>setPage(p=>p-1)}>이전</button><span>{page+1} / {Math.max(1,Math.ceil(count/50))}</span><button disabled={(page+1)*50>=count||loading||!!busy} onClick={()=>setPage(p=>p+1)}>다음</button></div></main>;
}
