'use client';
import {useRef,useState} from 'react';
import type {AccountDirection,Profile} from '@/lib/studio';
export function AccountDirections({profile,onChange,onRecommend,disabled}:{profile:Profile;onChange:(p:Profile)=>void;onRecommend:(p:Profile)=>Promise<AccountDirection[]>;disabled:boolean}){
 const [pending,setPending]=useState(false),[error,setError]=useState('');const latest=useRef(profile);latest.current=profile;
 const ready=[profile.niche,profile.audience,profile.strengths,profile.goal,profile.face].every(x=>x.trim());
 async function recommend(){const input=profile;setPending(true);setError('');try{const directions=await onRecommend(input);if(JSON.stringify(latest.current)!==JSON.stringify(input))throw Error('입력이 바뀌었습니다. 변경된 내용으로 다시 추천해 주세요.');onChange({...input,directions});}catch(e){setError(e instanceof Error?e.message:'추천을 완료하지 못했습니다.');}finally{setPending(false);}}
 return <section className="account-directions"><h3>나에게 맞는 계정 방향 찾기</h3><p>주제·시청자·경험과 제작 여건에 맞춰 서로 다른 방향 3개를 제안합니다. 선택 후 직접 수정할 수 있어요.</p>{([['goal','운영 목적','예: 일상 기록, 브랜드 협업, 전문 지식 공유'],['strengths','나의 경험·강점','실제로 해본 일, 잘 설명할 수 있는 분야, 꾸준히 만들 수 있는 소재'],['preferences','원하는 분위기·제작 여건','예: 담백한 유머, 주 2회 촬영, 얼굴 없이 목소리만'],['avoid','피하고 싶은 표현·방향','예: 나이 강조, 과한 감탄, 광고 말투']] as const).map(([key,label,placeholder])=><div className="field" key={key}><label htmlFor={'account-'+key}>{label}</label><textarea id={'account-'+key} rows={2} maxLength={key==='strengths'?1000:key==='preferences'?600:key==='avoid'?500:400} value={profile[key]} disabled={pending} placeholder={placeholder} onChange={e=>onChange({...profile,[key]:e.target.value})}/></div>)}{!ready&&<p>주로 다루는 분야, 시청자, 촬영 방식, 운영 목적, 경험·강점을 입력하면 추천받을 수 있어요.</p>}<button className="secondary" disabled={disabled||pending||!ready} onClick={recommend}>{pending?'계정 방향을 추천하고 있어요…':'계정 방향 3개 추천받기'}</button>{error&&<p role="alert">{error}</p>}<div className="direction-options">{profile.directions.map((d,i)=><article className="panel" key={i}><h4>{d.name}</h4><p>{d.positioning}</p><p><strong>추천 이유</strong> · {d.reason}</p><p>말투 · {d.tone}</p><ul>{d.pillars.map((v,j)=><li key={j}>{v}</li>)}</ul><strong>콘텐츠 아이디어 · 실제 경험 주장 아님</strong><ul>{d.examples.map((v,j)=><li key={j}>{v}</li>)}</ul><p>피할 방향 · {d.avoid}</p><button className="secondary" disabled={pending} onClick={()=>onChange({...profile,direction:[d.name,d.positioning,'말투: '+d.tone,'콘텐츠 축: '+d.pillars.join(' / '),'피할 방향: '+d.avoid].join('\n')})}>이 방향 선택 · {i+1}</button></article>)}</div><div className="field"><label htmlFor="account-direction">선택한 계정 방향 · 직접 수정 가능</label><textarea id="account-direction" value={profile.direction} maxLength={3000} rows={5} onChange={e=>onChange({...profile,direction:e.target.value})}/></div><p>아래 프로필 저장을 누르면 다음 기획에도 적용됩니다. 연령·성별·국적은 직접 제공한 경우에만 사용합니다.</p></section>;
}
