'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Brief,Result} from '@/lib/studio';
function TextPreview({value}:{value:Result}){return <div className="revision-copy"><h4>제목</h4><p>{value.title}</p><h4>썸네일</h4><p>{value.thumbnail}</p><small>{value.thumbnailKorean}</small><h4>후킹</h4>{value.hooks.map((h,i)=><p key={i}>{h.text}<br/><small>{h.korean}</small></p>)}<h4>대본</h4>{value.blocks.map(b=><section key={b.id}><strong>{b.label}</strong><p>{b.text}</p><small>{b.korean}</small><p>촬영·편집: {b.direction}</p></section>)}<h4>본문</h4><p>{value.caption}</p><small>{value.captionKorean}</small><h4>키워드 · 해시태그</h4><p>{value.keywords.join(' · ')}<br/>{value.hashtags.join(' ')}</p><h4>수정 참고</h4>{value.reviewNotes.map((n,i)=><p key={i}>{n}</p>)}</div>;}
export function FullRewrite({result,brief,disabled,onGenerate,onApply}:{result:Result;brief:Brief;disabled:boolean;onGenerate:(instruction:string,structure:'keep'|'rebuild')=>Promise<Result>;onApply:(r:Result)=>void}){
 const [open,setOpen]=useState(false),[instruction,setInstruction]=useState(''),[structure,setStructure]=useState<'keep'|'rebuild'>('keep'),[pending,setPending]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<Result|null>(null);
 const presets=brief.platform==='red'?[
 ['샤오홍슈 자연스러운 또래 말투','중국 20~30대가 샤오홍슈에서 친구에게 자기 경험을 공유하듯 자연스럽게 고쳐줘. 번역투와 광고 말투를 줄이고 짧은 구어체, 구체적인 공감 포인트로 후킹과 전체 흐름을 다듬어줘. 억지 유행어와 과장은 빼줘.'],
 ['후킹과 흐름 강화','확인된 내용 중 가장 눈길을 끄는 포인트로 시작하고, 끝까지 자연스럽게 이어지도록 전체 흐름을 고쳐줘. 제목·썸네일·본문도 같은 이야기로 맞춰줘.'],
 ['더 담백하고 솔직하게','광고처럼 들리는 표현과 과한 감탄을 줄이고, 내가 실제 경험한 내용만 담백하고 솔직하게 전달해줘.']
 ]:[['미국 TikTok 대화체','미국 20~30대가 친구에게 이야기하듯 짧고 자연스러운 대화체로 바꾸고 첫 장면부터 핵심이 드러나도록 전체 흐름을 다듬어줘. 억지 유행어나 과장은 빼줘.'],['후킹과 흐름 강화','확인된 사실로 강한 첫 장면을 만들고 전체 이야기의 흐름과 마무리를 다듬어줘.']];
 async function generate(){if(pending)return;setPending(true);setError('');setPreview(null);try{setPreview(await onGenerate(instruction,structure));}catch(e){setError(e instanceof Error?e.message:'수정안을 만들지 못했어요.');}finally{setPending(false);}}
 return <><button className="secondary" disabled={disabled} onClick={()=>{setOpen(true);setPreview(null);setError('');}}>전체 대본 AI 수정</button><Dialog open={open} onOpenChange={v=>{if(!pending)setOpen(v);}}><DialogContent className="full-rewrite-dialog" style={{maxWidth:1100,width:'min(1100px, 95vw)',maxHeight:'90vh',overflowY:'auto'}}><DialogHeader><DialogTitle>전체 대본 AI 수정</DialogTitle><DialogDescription>제목·썸네일·후킹·대본·본문과 한국어 의미를 함께 다듬습니다. 수정안을 비교한 후 적용해 주세요.</DialogDescription></DialogHeader><div className="revision-presets">{presets.map(([label,text])=><button className="secondary" key={label} disabled={pending} onClick={()=>{setInstruction(v=>(v?v+'\n':'')+text);setPreview(null);}}>{label}</button>)}</div><div className="field"><label htmlFor="whole-instruction">전체 수정 요청</label><textarea id="whole-instruction" rows={4} maxLength={2000} disabled={pending} value={instruction} onChange={e=>{setInstruction(e.target.value);setPreview(null);}} placeholder="예: 첫 장면은 바뀐 머리 모습으로 시작하고, 친구에게 말하듯 가볍게. 광고 같은 표현은 빼고 제목과 본문도 함께 바꿔 줘."/></div><div className="field"><label htmlFor="whole-structure">장면 구성</label><select id="whole-structure" disabled={pending} value={structure} onChange={e=>{setStructure(e.target.value as 'keep'|'rebuild');setPreview(null);}}><option value="keep">현재 장면·순서·시간 유지</option><option value="rebuild">전체 흐름 재구성 허용</option></select></div><p>새로운 사실·후기는 정보 확인 단계에서 추가해 주세요. 수정 요청만으로 경험을 새로 만들지는 않습니다.</p>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={pending||!instruction.trim()||instruction.length>2000} onClick={generate}>{pending?'전체 수정안을 만들고 있어요…':'전체 수정안 만들기'}</button>{preview&&<><div className="revision-comparison"><section><h3>수정 전</h3><TextPreview value={result}/></section><section><h3>수정 후</h3><TextPreview value={preview}/></section></div><button className="primary" onClick={()=>{onApply(preview);setOpen(false);setPreview(null);}}>전체 수정안 적용</button></>}<button className="secondary" disabled={pending} onClick={()=>setOpen(false)}>닫기 · 원본 유지</button></DialogContent></Dialog></>;
}
