import {lookup} from 'node:dns/promises';
import {request} from 'node:https';
import {isIP} from 'node:net';
export const GUIDE_BYTES=10*1024*1024;
export function publicIPv4(ip:string){if(isIP(ip)!==4)return false;const [a,b]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a>=224||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&(b===168||b===0))||(a===198&&(b===18||b===19))||(a===192&&b===2)||(a===198&&b===51)||(a===203&&b===0));}
export function guideURL(value:string){let u:URL;try{u=new URL(value);}catch{throw Error('올바른 공개 링크를 입력해 주세요.');}if(u.protocol!=='https:'||u.username||u.password||(u.port&&u.port!=='443')||u.hostname.startsWith('[')||u.hostname==='localhost'||u.hostname.endsWith('.local')||u.hostname.endsWith('.internal')||(isIP(u.hostname)&&!publicIPv4(u.hostname)))throw Error('로그인 없이 열 수 있는 공개 HTTPS 링크를 입력해 주세요.');return u;}
export function fileMime(bytes:Buffer){if(bytes.subarray(0,5).toString()==='%PDF-')return 'application/pdf';if(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return 'image/png';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';if(bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP')return 'image/webp';return null;}
// Pin a validated public address on every request, including every redirect.
export async function readGuideURL(value:string,hops=0):Promise<{bytes:Buffer;type:string;url:string}>{
 if(hops>3)throw Error('링크 이동이 너무 많습니다. PDF를 업로드해 주세요.');
 const url=guideURL(value);const addresses=await lookup(url.hostname,{all:true,family:4});if(!addresses.length||addresses.some(a=>!publicIPv4(a.address)))throw Error('접근할 수 없는 링크입니다. PDF를 업로드해 주세요.');
 const response=await new Promise<{status:number;location?:string;bytes:Buffer;type:string}>((resolve,reject)=>{const req=request(url,{method:'GET',headers:{Accept:'application/pdf,text/html,image/*','User-Agent':'GlobalViral-GuideReader/1.0'},lookup:(_host,_options,cb)=>cb(null,addresses[0].address,4)},res=>{const status=res.statusCode??500;if(status>=300&&status<400){res.resume();resolve({status,location:res.headers.location,bytes:Buffer.alloc(0),type:''});return;}if(status!==200){res.resume();reject(Error('링크를 읽지 못했습니다. 공개 보기 권한을 확인하거나 PDF·이미지를 업로드해 주세요.'));return;}let size=0;const parts:Buffer[]=[];res.on('data',(chunk:Buffer)=>{size+=chunk.length;if(size>GUIDE_BYTES){res.destroy();reject(Error('가이드는 최대 10MB까지 읽을 수 있습니다.'));return;}parts.push(chunk);});res.on('error',reject);res.on('end',()=>resolve({status,bytes:Buffer.concat(parts),type:res.headers['content-type']??''}));});const timer=setTimeout(()=>req.destroy(Error('링크 읽기 시간이 초과되었습니다. PDF를 업로드해 주세요.')),15000);req.on('close',()=>clearTimeout(timer));req.on('error',reject);req.end();});
 if(response.location)return readGuideURL(new URL(response.location,url).href,hops+1);if(response.status!==200)throw Error('링크가 유효하지 않습니다.');return {...response,url:url.href};
}
export function htmlText(html:string){return html.replace(/<(script|style|noscript|svg|head)\b[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Math.min(Number(n),0x10ffff))).replace(/\s+/g,' ').trim();}
