import {z} from 'zod';
export const referenceStyleSchema=z.enum(['auto','review','curation','lifestyle','travel','day','none']);
export type ReferenceStyle=z.infer<typeof referenceStyleSchema>;
export const referenceGuides=[
 {id:'review',name:'실사용 리뷰형',summary:'평가 관점 → 제품 디테일 → 사용 장면 → 상황별 선택 기준',visual:'인물 또는 손과 제품을 함께 보여주고, 제형·발색·사용 장면을 교차해요.',cover:'제품과 실제 사용 컷 + 비교 기준 한 가지',rule:'Lead with an evidenced evaluation criterion, alternate explanation with product detail and actual application only when evidenced. Conclude with supported suitability, not a universal winner.'},
 {id:'curation',name:'취향·매장 큐레이션형',summary:'누구를 위한 추천인지 → 매장·제품별 차이 → 선택 기준',visual:'공간 전경·디테일·착용 또는 사용 컷을 설명 장면과 연결해요.',cover:'대표 공간·제품과 취향을 설명하는 짧은 문구',rule:'Specify the intended taste or situation. Alternate overview, detail and evidenced try-on/use. Use chapter labels for multiple items. Never invent local expertise or years of residence.'},
 {id:'lifestyle',name:'생활 속 발견형',summary:'실제 생활 속 계기 → 제품을 고른 이유 → 경험과 한계',visual:'일상 장면에서 제품으로 넘어가고 실제 사용 맥락을 보여줘요.',cover:'생활 장면과 핵심 제품 + 궁금한 선택 이유',rule:'Start from an evidenced everyday situation, connect to a selection reason and evidenced experience. Never import health, efficacy, repurchase or personal-history claims from a reference.'},
 {id:'travel',name:'여행·외출 하이라이트형',summary:'볼거리 미리보기 → 방문 흐름 → 기억할 디테일',visual:'인물·음식·공간의 짧은 도입 모음 이후 여정을 연결해요.',cover:'대표 장면 2~3개 콜라주 + 장소·분위기',rule:'Open with a compact preview of available highlights, then follow the evidenced journey with concrete details. Do not invent visits, travel order, transport, food reactions or weather.'},
 {id:'day',name:'하루 기록형',summary:'오늘의 장면 미리보기 → 행동의 흐름 → 작은 마무리',visual:'전체 구도와 손·사물 디테일을 섞고 시간·행동으로 구간을 나눠요.',cover:'하루를 대표하는 장면 + 상황을 알려주는 문구',rule:'Use an everyday sequence with wide and detail shots. Clock timestamps only if supplied; otherwise activity chapter labels. No invented productive routine, emotion, job or relationships.'}
] as const;
type GuideInput={referenceStyle?:ReferenceStyle;category:string;mode:string};
export function resolveReferenceGuide(brief:GuideInput){
 const chosen=brief.referenceStyle??'auto';
 if(chosen==='none')return null;
 const id=chosen!=='auto'?chosen:brief.category==='daily'?'day':brief.category==='vlog'?'travel':brief.category==='place'||brief.mode==='collection'?'curation':brief.mode==='routine'?'lifestyle':'review';
 return referenceGuides.find(g=>g.id===id)??null;
}
export function referenceInstructions(input:unknown,platform:'red'|'tiktok'){
 const brief=(input as {brief?:GuideInput})?.brief;if(!brief)return '';
 const guide=resolveReferenceGuide(brief);
 return `Production guidance for every planning, generation, review and revision task: ${guide?`Selected editorial guide: ${guide.name}. Structure: ${guide.summary}. ${guide.rule} Visual principle: ${guide.visual}. Cover principle: ${guide.cover}. These are abstract editorial observations from five supplied Xiaohongshu videos and account screenshots sampled on 2026-09-29, not verified trend/performance evidence. Never copy distinctive sentences, identities, facts or claims from references.`:'No reference style selected; derive a custom structure from the creator and confirmed facts.'}
Creator profile, face/voice constraints, preferences, avoid list, factual evidence and confirmed mandatory brand requirements take priority over the guide. Automatic guide matching is a category-based starting point; adapt it to the actual story. No gender, age, nationality or lifestyle assumptions. For face-free creators use hands, objects, environments or POV. Do not require speaking to camera if incompatible with profile.
Title names the subject/search intent and an evidenced angle; thumbnail is a short complementary promise; opening delivers a visual or spoken reason to continue. They must not repeat the same sentence. No unsupported clickbait, guaranteed results, fake repurchase or generic superlatives. Choose keywords from supplied subject, place and use case, not fabricated search-volume data.
${platform==='red'?'Use natural conversational Simplified Chinese for the specific audience. Visual atmosphere can be the hook for vlogs; do not force a sensational question or slang into every opening.':'Adapt to natural US English, a direct visual premise and concise spoken delivery. These Chinese reference structures are inspiration only, not evidence of current US slang; never translate Chinese memes literally.'}
When returning plans, include the opening visual and how the thumbnail will look in Korean outline entries, alongside the story sequence. When returning blocks, direction must be a concise actionable Korean production guide with line breaks: 영상: 촬영: shot size + subject/action; 보조 화면: available cutaway or explicitly optional shot; 편집: cut/transition and pace appropriate to the scene; 강조 자막: short platform-language text with Korean meaning, or 없음; 소리: optional ambience/music mood/voice guidance. First block also includes 썸네일 구도: layout, focal image and text placement. For cards use 화면 구성 / 강조 문구 / 다음 장 연결 instead; no video timings or audio instructions.
Production suggestions are not claims of recorded events. shootingStage=filmed: use only listed scenes; absent required footage must be marked 추가 촬영 필요 with a feasible existing-footage alternative. planned: mark 촬영 제안. Never invent clock times. Do not claim to inspect a video or link entered in notes. Fit the chosen duration with realistic speech and breathing room; group related cuts into at most 12 scene blocks. A 15-second video must focus on one takeaway instead of compressing a long reference. On review/revision preserve or update concrete production guidance along with changed script content. Do not put production directions into spoken text or its Korean translation.`;
}
