import { z } from 'zod';
export const profileSchema=z.object({name:z.string().max(80),niche:z.string().max(80),tone:z.string().max(80),audience:z.string().max(200),face:z.string().max(80)});
export type Profile=z.infer<typeof profileSchema>;
export const defaultProfile:Profile={name:'나의 크리에이터',niche:'뷰티 · 스킨케어',tone:'차분하고 솔직하게',audience:'한국 제품이 궁금한 중국어권 20–30대',face:'제품과 손만 촬영'};
export const briefSchema=z.object({name:z.string().min(1).max(150),url:z.string().max(1500),category:z.enum(['beauty','place','other']),platform:z.enum(['red','tiktok']),format:z.enum(['cards','video']),experience:z.enum(['none','used']),relationship:z.enum(['self','gift','paid','affiliate','none']),notes:z.string().max(4000),length:z.string().max(30),profile:profileSchema});
export type Brief=z.infer<typeof briefSchema>;
export const emptyBrief:Brief={name:'',url:'',category:'beauty',platform:'red',format:'cards',experience:'none',relationship:'none',notes:'',length:'6장',profile:defaultProfile};
export const factSchema=z.object({id:z.string().max(80),text:z.string().min(1).max(2000),source:z.string().max(1500),kind:z.enum(['official','review','experience','manual']),confirmed:z.boolean(),checkedAt:z.string().max(50)});
export type Fact=z.infer<typeof factSchema>;
export const blockSchema=z.object({id:z.string().max(80),label:z.string().max(100),text:z.string().max(4000),korean:z.string().max(4000),direction:z.string().max(2000)});
export type Block=z.infer<typeof blockSchema>;
export const resultSchema=z.object({title:z.string().max(500),hooks:z.array(z.object({text:z.string().max(1000),korean:z.string().max(1000)})).min(1).max(3),blocks:z.array(blockSchema).min(1).max(12),caption:z.string().max(6000),captionKorean:z.string().max(6000),hashtags:z.array(z.string().max(100)).max(8)});
export type Result=z.infer<typeof resultSchema>;
export const projectSchema=z.object({id:z.string().uuid(),brief:briefSchema,facts:z.array(factSchema).max(30),result:resultSchema.nullable(),concept:z.number().int().min(0).max(2),demo:z.boolean(),updatedAt:z.string().max(50)});
export type Project=z.infer<typeof projectSchema>;
export const concepts=[{title:'궁금증을 여는 발견형',tag:'DISCOVERY',description:'익숙한 고민에서 시작해 제품·공간의 특징을 하나씩 소개해요.',hook:'처음 보는 사람도 이해할 수 있게'},{title:'저장하고 싶은 체크리스트',tag:'SAVE-WORTHY',description:'구매·방문 전 확인할 내용을 정리해 정보의 가치를 높여요.',hook:'필요할 때 다시 꺼내 보는 콘텐츠'},{title:'디테일에 집중하는 관찰형',tag:'DETAIL-LED',description:'제형·패키지·공간 등 직접 보여줄 수 있는 장면을 중심으로 구성해요.',hook:'과장보다 구체적인 장면으로'}];
export type Finding={id:string;term:string;start:number;end:number;category:string;reason:string;suggestion:string;level:'high'|'context'};
const rules:{regex:RegExp;category:string;reason:string;suggestion:string;level:'high'|'context'}[]=[
 {regex:/100\s*[%％]\s*(有效|효과|보장)?|百分之百有效|무조건\s*효과|guaranteed\s+results/gi,category:'효과 단정',reason:'모든 사람에게 같은 효과를 보장하는 표현입니다. 근거와 적용 범위를 확인해 주세요.',suggestion:'效果因人而异',level:'high'},
 {regex:/第一|最好的|全网最低|최고의|세계\s*1위|the best/gi,category:'최상급·순위',reason:'객관적 순위나 비교 근거가 필요한 표현입니다. 순서·일반 문맥인지도 확인해 주세요.',suggestion:'值得了解的',level:'context'},
 {regex:/治愈|根治|영구\s*치료|완치|cures?\b/gi,category:'치료 효능',reason:'치료를 단정하는 문구는 제품의 허용된 효능·근거를 별도로 확인해야 합니다.',suggestion:'日常护理',level:'high'},
 {regex:/微信|加微|私信购买|카톡으로\s*구매/gi,category:'외부 구매 유도',reason:'외부 연락·거래 유도에 해당하는지 게시 맥락과 플랫폼 정책을 확인해 주세요.',suggestion:'请查看产品信息',level:'context'},
 {regex:/내돈내산|亲测|自费购入|用了7天|7일\s*(사용|써)|I tried|I used/gi,category:'실사용 주장',reason:'본인의 실제 구매·사용 경험으로 확인할 수 있는 내용인지 검토해 주세요.',suggestion:'구매 전 확인한 정보',level:'context'},
 {regex:/马上抢|最后机会|품절\s*임박|before it sells out/gi,category:'긴급성·희소성',reason:'현재 재고·판매 기간에 대한 확인 없이 긴급성을 단정하지 마세요.',suggestion:'购买前请确认库存',level:'context'}
];
export function reviewText(text:string):Finding[]{const out:Finding[]=[];for(const [ri,r] of rules.entries()){for(const m of text.matchAll(new RegExp(r.regex.source,r.regex.flags))){const start=m.index??0;const lang=/[가-힣]/.test(m[0])?'ko':/[一-龥]/.test(m[0])?'zh':'en';const fallback=lang==='ko'?['개인에 따라 다를 수 있어요','살펴볼 만한','일상적인 관리','제품 정보를 확인해 주세요','구매 전 확인한 정보','구매 전 재고를 확인해 주세요'][ri]:lang==='en'?['Results may vary','worth exploring','daily care','Check the product information','A closer look','Check availability before purchasing'][ri]:r.suggestion;out.push({id:`${ri}-${start}`,term:m[0],start,end:start+m[0].length,category:r.category,reason:r.reason,suggestion:fallback,level:r.level});}}return out.sort((a,b)=>a.start-b.start);}
export function resultText(r:Result){return [r.title,...r.hooks.map(h=>h.text),...r.blocks.map(b=>b.text),r.caption,r.hashtags.join(' ')].join('\n\n');}
export const demoBrief:Brief={...emptyBrief,name:'모닝듀 수분 세럼',notes:'가상의 제품으로 보는 기획 예시입니다. 실사용 후기가 아닌 구매 전 체크리스트를 만들고 싶어요.'};
export function makeDemo(platform:'red'|'tiktok',format:'cards'|'video',concept:number):Result{const zh=platform==='red';const text=zh?['保湿精华怎么选？先看这3点','先确认你需要什么','成分表，值得多看一眼','质地，要亲自感受','购买之前再确认','把清单留给下次选购']:['Before you pick a hydrating serum…','Start with your routine','Take a closer look at the ingredients','Texture is personal','Check before you buy','Your simple shopping checklist'];const ko=['수분 세럼을 고르기 전 확인할 3가지','내 루틴에 필요한 것이 무엇인지 먼저 확인해요','성분표와 제품 설명을 살펴봐요','제형과 사용감은 직접 확인해요','용량·가격·판매처를 구매 전에 확인해요','다음 구매 때 참고할 체크리스트'];const dirs=['제품 패키지와 제목을 함께 배치해요.','현재 사용하는 제품을 정리한 장면을 보여줘요.','패키지의 성분표를 확대해 촬영해요.','직접 촬영한 제형 영상이 있을 때만 사용해요.','확인된 제품 정보만 간결하게 배치해요.','세 가지 확인 항목을 한 화면에 정리해요.'];return {title:text[concept===1?5:0],hooks:[{text:text[0],korean:ko[0]},{text:zh?'选精华，先别急着跟风':'A serum checklist, without the hype',korean:'유행을 따르기 전에 확인해요'},{text:zh?'适不适合你？从这几步开始':'Is it right for your routine?',korean:'나에게 맞는지 확인하는 순서'}],blocks:text.map((t,i)=>({id:`demo-${i}`,label:format==='cards'?`${String(i+1).padStart(2,'0')} · ${i===0?'커버':i===5?'마무리':'내용'}`:`${i*5}–${(i+1)*5}초`,text:t,korean:ko[i],direction:dirs[i]})),caption:zh?'挑选护肤品时，先了解自己的需求，再查看产品信息。肤质与使用感因人而异，购买前请核对成分、规格与价格。':'Start with your needs, then review the product details. Skin and texture preferences vary. Check ingredients, size and price before buying.',captionKorean:'내 필요를 먼저 확인하고 제품 정보를 살펴보세요. 피부와 선호하는 사용감은 사람마다 다르므로 성분·용량·가격을 구매 전에 확인해요.',hashtags:zh?['#护肤思路','#保湿精华','#护肤清单']:['#SkincareRoutine','#Serum','#SkincareTips']};}
