'use client';
import {useEffect,useState,type FormEvent} from 'react';
type Mode='login'|'signup'|'reset'|'update';
export default function AuthForm({configured,initialMode='login'}:{configured:boolean;initialMode?:Mode}){
 const [mode,setMode]=useState<Mode>(initialMode);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('error'))setError('인증 링크가 만료되었거나 유효하지 않습니다. 가입 또는 비밀번호 재설정을 다시 요청해 주세요.');},[]);
 const titles={login:'다시 만나 반가워요',signup:'나의 글로벌 콘텐츠, 시작하기',reset:'비밀번호를 잊으셨나요?',update:'새 비밀번호 설정'};
 async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');if((mode==='signup'||mode==='update')&&password!==confirm){setError('비밀번호가 일치하지 않습니다.');return;}setBusy(true);
 try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,email,password})});const d=await r.json();if(!r.ok)throw Error(d.error);if(mode==='login')window.location.assign('/');else if(mode==='update')window.location.assign('/login');else setMessage(d.message);}catch(e){setError(e instanceof Error?e.message:'연결을 확인해 주세요.');}finally{setBusy(false);}}
 function change(m:Mode){setMode(m);setError('');setMessage('');setPassword('');setConfirm('');}
 return <main className="auth-shell"><section className="auth-story"><a className="auth-brand" href="/login">◉ GlobalViral</a><span className="auth-kicker">FOR GLOBAL CREATORS</span><h1>당신의 이야기를,<br/>더 넓은 세상으로.</h1><p>틱톡과 샤오홍슈를 위한 콘텐츠 기획.<br/>확인한 정보로 만들고, 표현까지 꼼꼼하게.</p><div className="auth-market">ENGLISH · 中文 · 한국어</div><small>수강생 전용 콘텐츠 스튜디오</small></section><section className="auth-panel"><div className="auth-card"><span className="auth-eyebrow">CREATOR WORKSPACE</span><h2>{titles[mode]}</h2><p>{mode==='signup'?'이메일 인증과 수강 승인을 거쳐 작업실을 이용할 수 있어요.':'나만의 콘텐츠와 프로젝트를 이어가세요.'}</p>{!configured&&<div className="auth-notice">로그인 서비스 연결 준비 중입니다. 운영 설정이 완료되면 이용할 수 있어요.</div>}
 <form onSubmit={submit}>{mode!=='update'&&<label>이메일<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>}{mode!=='reset'&&<label>비밀번호<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?1:12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='login'?'비밀번호 입력':'12자 이상 입력'}/></label>}{(mode==='signup'||mode==='update')&&<label>비밀번호 확인<input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}
 {error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p className="auth-notice" role="status">{message}</p>}<button className="auth-submit" disabled={!configured||busy}>{busy?'처리 중…':({login:'로그인',signup:'가입 신청',reset:'재설정 이메일 받기',update:'비밀번호 저장'})[mode]}</button></form>
 <div className="auth-links">{mode==='login'?<><button onClick={()=>change('signup')}>회원가입</button><button onClick={()=>change('reset')}>비밀번호 찾기</button></>:mode==='update'?<a href="/">작업실로 돌아가기</a>:<button onClick={()=>change('login')}>로그인으로 돌아가기</button>}</div><div className="auth-footnote">프로젝트는 내 계정에 저장됩니다.<br/>수강 권한은 운영자가 확인 후 승인합니다.</div></div></section></main>;
}
